delete process.env.ELECTRON_RUN_AS_NODE;
// Desktop integration checks run in a separate profile, without real credentials or requests.
const{_electron:electron}=require('playwright');const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),profile=path.join(root,'output','qa-profile');fs.mkdirSync(profile,{recursive:true});
const accounts=[['claude','Claude Code',6],['codex','Codex',89],['cursor','Cursor',2],['opencode','OpenCode Go',1],['kimi','Kimi Code',22],['zai','z.ai',15]].map(([id,label,used])=>({id,provider:id,label,enabled:true,dataPath:path.join(profile,'empty'),used}));
fs.writeFileSync(path.join(profile,'settings.json'),JSON.stringify({language:'en',collapse:false,position:'right',hideFullscreen:false,accounts:accounts.map(({used,...a})=>a)}));
fs.writeFileSync(path.join(profile,'cache.json'),JSON.stringify(Object.fromEntries(accounts.map(a=>[a.id,{status:'live',source:'QA fixture (not a real account)',observedAt:new Date().toISOString(),plan:'Test plan',windows:[{id:'primary',label:a.id==='cursor'?'Monthly limit · Cursor Models':'5-hour limit',used:a.used,resetsAt:new Date(Date.now()+3600000).toISOString(),seconds:18000,exhausted:false},{id:'weekly',label:a.id==='cursor'?'Monthly limit · Other Models':'Weekly limit',used:0,resetsAt:new Date(Date.now()+86400000).toISOString(),seconds:604800,exhausted:false}]}]))));
(async()=>{const errors=[];const executable=process.env.PULSE_QA_EXE;const application=await electron.launch({...(executable?{executablePath:executable,args:[]}:{args:[root]}),env:{...process.env,PULSE_TEST_MODE:'1',PULSE_TEST_DATA:profile}});try{
 await new Promise(r=>setTimeout(r,1800));const pages=application.windows();const settings=pages.find(p=>p.url().includes('settings'));const panel=pages.find(p=>p.url().includes('panel'));assert.ok(settings&&panel,'Both windows are created');for(const p of pages)p.on('pageerror',e=>errors.push(e.message));
 await settings.getByRole('heading',{name:'General',exact:true}).waitFor();await settings.screenshot({path:path.join(root,'output','settings-en.png')});
 // Native transparency and no-activation are verified via Electron itself.
 const flags=await application.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('view=panel'));return{focusable:w.isFocusable(),top:w.isAlwaysOnTop(),visible:w.isVisible()};});assert.deepEqual(flags,{focusable:false,top:true,visible:true});
 await panel.addStyleTag({content:'body{background:#f7f7f7}'});await panel.locator('.slot').nth(2).hover();await panel.locator('.usage-card').waitFor();await panel.screenshot({path:path.join(root,'output','panel.png'),omitBackground:true});
 await settings.getByRole('switch',{name:'Show remaining allowance'}).click();assert.equal((await settings.evaluate(()=>window.pulse.state())).settings.remaining,true);await settings.getByRole('switch',{name:'Show remaining allowance'}).click();
 await settings.locator('.nav-item').filter({hasText:'Codex'}).click();await settings.getByRole('heading',{name:'Codex',exact:true}).waitFor();await settings.getByTitle('Pin this limit to the ring').nth(1).click();assert.equal((await settings.evaluate(()=>window.pulse.state())).settings.accounts.find(a=>a.id==='codex').pin,'weekly');await settings.screenshot({path:path.join(root,'output','account.png')});
 await settings.locator('.nav-item').filter({hasText:'Token spend'}).click();await settings.getByText('No records in this period').waitFor();await settings.screenshot({path:path.join(root,'output','spend.png')});
 await settings.locator('.nav-item').filter({hasText:'About'}).click();await settings.getByRole('heading',{name:'Pulse for Windows'}).waitFor();assert.equal(await settings.getByText('github.com/qunqin24/Pulse',{exact:true}).count(),1);assert.equal(await settings.getByText('github.com/dcxa521gi/Pulse-Win',{exact:true}).count(),1);await settings.getByRole('button',{name:/Check for updates/}).click();await settings.getByText('You are using the latest version.').waitFor();await assert.rejects(()=>settings.evaluate(()=>window.pulse.openExternal('https://example.com')),/not allowed/);await settings.screenshot({path:path.join(root,'output','about.png')});
 await settings.locator('.nav-item.add-account').click();await settings.getByRole('dialog').getByRole('button',{name:'DeepSeek'}).click();assert.equal((await settings.evaluate(()=>window.pulse.state())).settings.accounts.length,7);
 await settings.locator('.nav-item').filter({hasText:'DeepSeek'}).click();await settings.getByRole('button',{name:'Remove account',exact:true}).click();await settings.getByRole('button',{name:'Remove',exact:true}).click();assert.equal((await settings.evaluate(()=>window.pulse.state())).settings.accounts.length,6);
 await settings.locator('.nav-item').filter({hasText:'General'}).click();await settings.getByRole('button',{name:'简体中文',exact:true}).click();await settings.getByRole('heading',{name:'通用',exact:true}).waitFor();await settings.locator('.content').evaluate(el=>el.scrollTop=0);await settings.screenshot({path:path.join(root,'output','settings-zh.png')});
 await settings.evaluate(()=>window.pulse.settings({position:'top',collapse:false}));await new Promise(r=>setTimeout(r,400));await panel.locator('.slot').nth(2).hover();await panel.locator('.usage-card').waitFor();await panel.screenshot({path:path.join(root,'output','panel-top.png'),omitBackground:true});
 await settings.evaluate(()=>window.pulse.settings({position:'left',collapse:true}));await panel.mouse.move(350,10);await new Promise(r=>setTimeout(r,1000));assert.ok(await panel.locator('.rail').evaluate(el=>el.classList.contains('collapsed')));
 await settings.evaluate(()=>window.pulse.credential('claude','synthetic-qa-secret'));assert.equal(fs.readFileSync(path.join(profile,'credentials.json'),'utf8').includes('synthetic-qa-secret'),false);await settings.evaluate(()=>window.pulse.credential('claude',''));assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'PASS',checks:['settings render','non-activating always-on-top window','hover detail','setting persistence','limit pin','ledger empty state','about and updater UI','external URL allowlist','add/remove account','Chinese UI','top docking','auto collapse','no renderer errors'],screenshots:6}));
 }finally{await application.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
