const{test}=require('node:test');const assert=require('node:assert/strict');const{parse,credentials}=require('../electron/providers.cjs');
test('Antigravity real captured schema is inverted from remaining',()=>{const r=parse('antigravity',require('./fixtures/antigravity-quota.json'));assert.equal(r.windows.length,4);assert.ok(r.windows[0].used>.5&&r.windows[0].used<.6);});
test('Volcengine skips unknown, unsubscribed and failed plans',()=>{const r=parse('volcengine',require('./fixtures/volcengine-arkcli-usage.json'));assert.equal(r.windows.length,4);assert.equal(r.windows[0].used,41.5);});
test('Devin captured percentages are already used, no double inversion',()=>{const r=parse('devin',require('./fixtures/devin-quota-usage.json'));assert.equal(r.windows[0].used,2);assert.equal(r.windows[1].used,1);});
test('Command Code captured credits are a remaining balance',()=>{const r=parse('command',require('./fixtures/command-code-credits.json'));assert.match(r.balance,/USD/);});
test('Grok proto3 omitted percent is zero only for an active valid period',()=>{const r=parse('grok',{config:{currentPeriod:{start:new Date(Date.now()-1000).toISOString(),end:new Date(Date.now()+1000).toISOString()}}});assert.equal(r.windows[0].used,0);assert.throws(()=>parse('grok',{config:{}}));});
test('Grok Bot excludes no-allowance and missing percentages',()=>{assert.throws(()=>parse('grokbot',{hasNonZeroIncludedLimit:false,usagePercent:0}));const r=parse('grokbot',{hasNonZeroIncludedLimit:true,usagePercent:12});assert.equal(r.windows[0].used,12);});
test('Ollama requires explicit percentages in both independent windows',()=>{const html='<section data-usage-meter><h3>Session usage</h3><span>12% used</span></section><section data-usage-meter><h3>Weekly usage</h3><span>7% used</span></section>';const r=parse('ollama',html);assert.deepEqual(r.windows.map(w=>w.used),[12,7]);assert.throws(()=>parse('ollama','<h3>Session usage</h3>'));});
test('MiniMax weekly counters describe remaining, not used',()=>{const r=parse('minimax',{model_remains:[{current_weekly_total_count:100,current_weekly_usage_count:75}]});assert.equal(r.windows[0].used,25);assert.equal(r.windows[0].label,'Weekly limit');});
