const{execFile}=require('node:child_process');const path=require('node:path');const https=require('node:https');
function exec(file,args,options={}){return new Promise((resolve,reject)=>execFile(file,args,{windowsHide:true,timeout:15000,maxBuffer:2*1024*1024,...options},(e,out)=>e?reject(Error('Local client is not running or not signed in')):resolve(out)));}
async function fetchLocal(provider){
 if(provider==='volcengine'){const output=await exec('arkcli.exe',['usage','plan','--format','json']);try{return JSON.parse(output);}catch{throw Error('No readable quota reported');}}
 const{app}=require('electron');const script=app.isPackaged?path.join(process.resourcesPath,'antigravity.ps1'):path.join(__dirname,'antigravity.ps1');const output=await exec('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',script]);let servers;try{servers=JSON.parse(output);}catch{throw Error('Local client is not running or not signed in');}
 for(const server of servers.slice(0,6))for(const port of server.ports.slice(0,6)){if(!Number.isInteger(port)||port<1||port>65535||typeof server.token!=='string')continue;try{const body=await new Promise((resolve,reject)=>{const request=https.request({hostname:'127.0.0.1',port,path:'/exa.language_server_pb.LanguageServerService/RetrieveUserQuotaSummary',method:'POST',rejectUnauthorized:false,headers:{'Content-Type':'application/json','x-codeium-csrf-token':server.token},timeout:1800},res=>{let data='';res.on('data',c=>{data+=c;if(data.length>2*1024*1024)request.destroy();});res.on('end',()=>res.statusCode===200?resolve(data):reject(Error('No quota')));});request.on('error',reject);request.on('timeout',()=>request.destroy(Error('Timeout')));request.end('{}');});const r=JSON.parse(body);if((r.response?.groups||r.groups)?.length)return r;}catch{}}
 throw Error('Local client is not running or not signed in');
}
async function codexLimits(dataPath){
 const{spawn}=require('node:child_process');const fs=require('node:fs');let binary='codex.exe';
 try{const candidates=(await exec('where.exe',['codex.exe'])).trim().split(/\r?\n/);if(candidates[0])binary=candidates[0];}catch{const root=path.join(process.env.LOCALAPPDATA||'','OpenAI','Codex','bin');try{const choices=fs.readdirSync(root).map(d=>path.join(root,d,'codex.exe')).filter(f=>fs.existsSync(f));choices.sort((a,b)=>fs.statSync(b).mtimeMs-fs.statSync(a).mtimeMs);if(choices[0])binary=choices[0];}catch{}}
 return new Promise((resolve,reject)=>{const child=spawn(binary,['app-server'],{windowsHide:true,stdio:['pipe','pipe','ignore'],env:{...process.env,...(dataPath?{CODEX_HOME:dataPath}:{})}});let buffer='',done=false;const finish=(error,result)=>{if(done)return;done=true;clearTimeout(timer);child.stdin.end();child.kill();error?reject(Error('Local client is not running or not signed in')):resolve(result);};const timer=setTimeout(()=>finish(true),22000);child.on('error',()=>finish(true));child.on('exit',()=>{if(!done)finish(true);});child.stdin.on('error',()=>finish(true));const send=(id,method,params={})=>child.stdin.write(JSON.stringify({jsonrpc:'2.0',...(id?{id}:{}),method,params})+'\n');child.stdout.on('data',chunk=>{buffer+=chunk;if(buffer.length>2*1024*1024)return finish(true);let index;while((index=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,index);buffer=buffer.slice(index+1);let r;try{r=JSON.parse(line);}catch{continue;}if(r.id===1){if(r.error)return finish(true);send(null,'initialized');send(2,'account/rateLimits/read');}if(r.id===2)finish(!!r.error,r.result);}});send(1,'initialize',{clientInfo:{name:'pulse_windows',title:'Pulse',version:'1.0.1'}});});
}
module.exports={fetchLocal,exec,codexLimits};
