const {app,BrowserWindow,ipcMain,Tray,Menu,nativeImage,screen,safeStorage,net,dialog,Notification,globalShortcut,shell}=require('electron');
const path=require('node:path');const fs=require('node:fs');const crypto=require('node:crypto');const {Worker}=require('node:worker_threads');
const {Storage}=require('./storage.cjs');const {catalog,fetchUsage,credentials}=require('./providers.cjs');
app.setAppUserModelId('org.pulse.windows');
const testMode=process.env.PULSE_TEST_MODE==='1';if(testMode)app.setPath('userData',path.resolve(process.env.PULSE_TEST_DATA||'output/test-profile'));
let store,panel,settingsWindow,tray,dragging=null,areas=[],refreshTimer,watcher,ledgerPromise,ledgerResult;
const pending=new Map(),alerts=new Map();let lastAutomatic=0;let fullscreen=false,fullscreenHelper;
let updateState={status:'idle'};let updaterReady=false;
const externalURLs=new Set(['https://github.com/qunqin24/Pulse','https://github.com/qunqin24/Pulse/blob/main/LICENSE','https://github.com/dcxa521gi/Pulse-Win','https://github.com/dcxa521gi/Pulse-Win/releases']);
function publishUpdate(state){updateState={...updateState,...state};for(const w of [settingsWindow])if(w&&!w.isDestroyed())w.webContents.send('update-state',updateState);return updateState;}
function configureUpdater(){if(!app.isPackaged||testMode)return;const{autoUpdater}=require('electron-updater');autoUpdater.autoDownload=false;autoUpdater.autoInstallOnAppQuit=true;autoUpdater.on('checking-for-update',()=>publishUpdate({status:'checking',message:undefined}));autoUpdater.on('update-available',info=>publishUpdate({status:'available',version:info.version}));autoUpdater.on('update-not-available',()=>publishUpdate({status:'not-available',version:app.getVersion()}));autoUpdater.on('download-progress',p=>publishUpdate({status:'downloading',percent:Math.round(p.percent)}));autoUpdater.on('update-downloaded',info=>publishUpdate({status:'downloaded',version:info.version,percent:100}));autoUpdater.on('error',error=>publishUpdate({status:'error',message:String(error?.message||'Update check failed').replace(/https?:\/\/\S+/g,'')}));updaterReady=true;setTimeout(()=>autoUpdater.checkForUpdates().catch(()=>{}),15000);}
function watchFullscreen(){if(process.platform!=='win32'||testMode)return;const script=app.isPackaged?path.join(process.resourcesPath,'fullscreen.ps1'):path.join(__dirname,'fullscreen.ps1');fullscreenHelper=require('node:child_process').spawn('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',script,'-ParentId',String(process.pid)],{windowsHide:true,stdio:['ignore','pipe','ignore']});fullscreenHelper.stdout.on('data',data=>{fullscreen=data.toString().trim().split(/\s+/).at(-1)==='1';if(!panel||panel.isDestroyed())return;if(fullscreen&&store.settings.hideFullscreen)panel.hide();else if(store.settings.visible)panel.showInactive();});fullscreenHelper.on('error',()=>{});}
const available=catalog.map(p=>p.id);
function state(){return {version:app.getVersion(),catalog:catalog.map(p=>({...p,available:available.includes(p.id)})),settings:store.settings,readings:Object.fromEntries(Object.entries(store.cache).map(([id,{_identity,...r}])=>[id,r])),configured:Object.keys(store.secrets),refreshing:[...pending.keys()]};}
function broadcast(){for(const w of [panel,settingsWindow])if(w&&!w.isDestroyed())w.webContents.send('state',state());}
function secure(w){w.webContents.setWindowOpenHandler(()=>({action:'deny'}));w.webContents.on('will-navigate',(event)=>event.preventDefault());w.webContents.on('will-attach-webview',e=>e.preventDefault());}
function load(w,view){secure(w);return w.loadFile(path.join(__dirname,'../dist/index.html'),{query:{view}});}
function showSettings(){if(settingsWindow&&!settingsWindow.isDestroyed()){settingsWindow.show();settingsWindow.focus();return;}settingsWindow=new BrowserWindow({width:1040,height:790,minWidth:850,minHeight:620,frame:false,backgroundColor:'#ffffff',show:false,icon:path.join(__dirname,'../dist/icon.png'),webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});load(settingsWindow,'settings');settingsWindow.once('ready-to-show',()=>settingsWindow.show());settingsWindow.on('closed',()=>settingsWindow=null);}
function scale(){return {small:.85,standard:1,large:1.2}[store.settings.size]||1;}
function place(display){if(!panel)return;const s=store.settings;const d=display||screen.getAllDisplays().find(d=>d.id===s.display)||screen.getPrimaryDisplay();const b=d.workArea;const k=scale();const top=s.position==='top';const count=s.accounts.filter(a=>a.enabled).length||1;const length=Math.min(Math.round((92+count*58+Math.max(0,count-1)*({tight:16,standard:30,loose:40}[s.spacing]||30))*k),top?b.width-40:b.height-32);
 const width=top?Math.max(360,length):Math.round(362*k),height=top?Math.round(420*k):Math.max(340,Math.min(b.height-16,length+16));
 let x=s.position==='left'?b.x:s.position==='right'?b.x+b.width-width:b.x+Math.round((b.width-width)/2),y=top?b.y:b.y+Math.round((b.height-height)/2);
 if(s.position==='free'&&s.freePosition){x=Math.max(b.x,Math.min(b.x+b.width-width,s.freePosition.x));y=Math.max(b.y,Math.min(b.y+b.height-height,s.freePosition.y));}
 panel.setBounds({x,y,width,height});}
function makePanel(){panel=new BrowserWindow({width:362,height:500,frame:false,transparent:true,hasShadow:false,resizable:false,skipTaskbar:true,alwaysOnTop:true,focusable:false,show:false,webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true,backgroundThrottling:false}});panel.setAlwaysOnTop(true,'floating');panel.setIgnoreMouseEvents(true,{forward:true});load(panel,'panel');panel.once('ready-to-show',()=>{place();if(store.settings.visible)panel.showInactive();});panel.on('close',e=>{if(!app.isQuitting){e.preventDefault();store.settings.visible=false;store.save();panel.hide();broadcast();}});}
function menu(){return Menu.buildFromTemplate([{label:'Pulse · Windows',enabled:false},{type:'separator'},{label:'设置 / Settings',click:showSettings},{label:'显示悬浮窗 / Show panel',type:'checkbox',checked:store.settings.visible,click:()=>updateSettings({visible:!store.settings.visible})},{label:'刷新额度 / Refresh',click:()=>refreshAll()},{type:'separator'},{label:'退出 / Quit',click:()=>{app.isQuitting=true;app.quit();}}]);}
function traySetup(){const icon=nativeImage.createFromPath(path.join(__dirname,'../dist/icon.png')).resize({width:32,height:32});tray=new Tray(icon);tray.setToolTip('Pulse — AI coding allowances');tray.setContextMenu(menu());tray.on('double-click',showSettings);}
function updateSettings(p){
 const allowed={language:['en','zh'],size:['small','standard','large'],spacing:['tight','standard','loose'],position:['left','right','top','free']};
 const bool=['visible','collapse','percentages','remaining','secondRing','clock','glass','followDisplay','hideFullscreen','launchAtLogin','notifications'];const patch={};
 for(const [k,v] of Object.entries(p||{})){if(allowed[k]?.includes(v))patch[k]=v;else if(bool.includes(k)&&typeof v==='boolean')patch[k]=v;else if(k==='refreshSeconds'&&[60,120,300,600].includes(v))patch[k]=v;else if(k==='warning'&&[60,70,75,80,90].includes(v))patch[k]=v;else if(k==='shortcut'&&typeof v==='string'&&v.length<80)patch[k]=v;}
 if(patch.shortcut!==undefined){globalShortcut.unregisterAll();if(patch.shortcut&&!globalShortcut.register(patch.shortcut,()=>updateSettings({visible:!store.settings.visible}))){if(store.settings.shortcut)globalShortcut.register(store.settings.shortcut,()=>updateSettings({visible:!store.settings.visible}));throw Error('Shortcut unavailable');}}
 Object.assign(store.settings,patch);store.save();if(patch.launchAtLogin!==undefined&&!testMode)app.setLoginItemSettings({openAtLogin:patch.launchAtLogin,args:['--background']});place();store.settings.visible&&!(fullscreen&&store.settings.hideFullscreen)?panel.showInactive():panel.hide();tray?.setContextMenu(menu());schedule();broadcast();return state();
}
async function refresh(id){const a=store.settings.accounts.find(a=>a.id===id);if(!a||!available.includes(a.provider))return;if(pending.has(id))return pending.get(id);
 const credential=credentials(a,store.secret(id));const identity=crypto.createHash('sha256').update(JSON.stringify([a.provider,a.dataPath||'',credential?.accountId||'',credential?.token||'local'])).digest('hex');if(store.cache[id]?._identity!==identity)delete store.cache[id];
 const task=(async()=>{try{const result=await fetchUsage(a,store.secret(id),(url,opts)=>net.fetch(url,opts));if(!store.settings.accounts.some(x=>x.id===id))return;store.cache[id]={...result,_identity:identity};const max=Math.max(0,...result.windows.map(w=>w.used));const previous=alerts.get(id)||0;const step=[75,80,90,95,100].filter(n=>max>=n).at(-1)||0;if(store.settings.notifications&&step>previous&&Notification.isSupported())new Notification({title:`Pulse · ${a.label}`,body:`额度已使用 ${Math.round(max)}%`}).show();alerts.set(id,step);}catch(e){const old=store.cache[id];const known=String(e.message);const safe=/^(Sign in|Login expired|Rate limited|Service returned HTTP|No readable|Service rejected|This Windows|Local client)/.test(known)?known:'Network request failed. Check your connection or system proxy';store.cache[id]={...(old||{windows:[],observedAt:null}),_identity:identity,status:old?.observedAt?'stale':'unavailable',error:safe,checkedAt:new Date().toISOString()};}finally{pending.delete(id);store.saveCache();broadcast();}})();pending.set(id,task);broadcast();return task;}
async function refreshAll(){const accounts=store.settings.accounts.filter(a=>a.enabled);for(let i=0;i<accounts.length;i+=3)await Promise.all(accounts.slice(i,i+3).map(a=>refresh(a.id)));}
function schedule(){clearInterval(refreshTimer);refreshTimer=setInterval(()=>{if(!testMode)refreshAll();},store.settings.refreshSeconds*1000);}
function trusted(event){return [panel,settingsWindow].some(w=>w&&!w.isDestroyed()&&event.sender===w.webContents)&&event.senderFrame===event.sender.mainFrame;}
function handle(name,fn){ipcMain.handle(name,async(e,...args)=>{if(!trusted(e))throw Error('Untrusted sender');return fn(...args);});}
function setupIPC(){
 handle('state',()=>state());handle('settings',updateSettings);handle('refresh',async id=>{if(id)await refresh(id);else await refreshAll();return state();});
 handle('account',a=>{if(!a||!catalog.some(p=>p.id===a.provider))throw Error('Unknown provider');const existing=store.settings.accounts.find(x=>x.id===a.id);const next={id:existing?.id||crypto.randomUUID(),provider:existing?.provider||a.provider,label:String(a.label||catalog.find(p=>p.id===a.provider).name).slice(0,60),enabled:typeof a.enabled==='boolean'?a.enabled:true,pin:typeof a.pin==='string'?a.pin.slice(0,120):'',color:/^#[0-9a-f]{6}$/i.test(a.color)?a.color:'',dataPath:existing?.dataPath||''};if(!next.enabled&&!store.settings.accounts.some(x=>x.id!==next.id&&x.enabled))throw Error('Keep at least one account visible');if(existing)Object.assign(existing,next);else{if(store.settings.accounts.length>=24)throw Error('Maximum 24 accounts');store.settings.accounts.push(next);}store.save();place();broadcast();return state();});
 handle('remove',id=>{if(pending.has(id))throw Error('Wait for refresh');if(!store.settings.accounts.some(a=>a.id!==id&&a.enabled))throw Error('Keep at least one account visible');store.settings.accounts=store.settings.accounts.filter(a=>a.id!==id);store.setSecret(id,'');store.save();place();broadcast();return state();});
 handle('credential',({id,value})=>{if(!store.settings.accounts.some(a=>a.id===id)||typeof value!=='string'||value.length>16000||/[\r\n]/.test(value))throw Error('Invalid credential');if(pending.has(id))throw Error('Wait for the refresh to finish');store.setSecret(id,value.trim());broadcast();return state();});
 handle('choosePath',async id=>{const a=store.settings.accounts.find(a=>a.id===id);if(!a)return;const r=await dialog.showOpenDialog(settingsWindow,{properties:['openDirectory'],title:'选择 .codex 或 .claude 数据目录（可选择 WSL 目录）'});if(!r.canceled){a.dataPath=r.filePaths[0];delete store.cache[id];store.save();store.saveCache();broadcast();}return state();});
 handle('ledger',days=>{if(![7,30,90].includes(days))throw Error('Invalid range');if(ledgerPromise)return ledgerPromise;ledgerPromise=new Promise(resolve=>{const worker=new Worker(path.join(__dirname,'ledger.cjs'),{workerData:{days,codexPath:store.settings.accounts.find(a=>a.provider==='codex')?.dataPath,claudePath:store.settings.accounts.find(a=>a.provider==='claude')?.dataPath}});const timeout=setTimeout(()=>{worker.terminate();resolve({rows:[],error:true,filesRead:0,skipped:1});},60000);worker.once('message',r=>{clearTimeout(timeout);ledgerResult=r;resolve(r);});worker.once('error',()=>{clearTimeout(timeout);resolve({rows:[],error:true,filesRead:0,skipped:1});});}).finally(()=>ledgerPromise=null);return ledgerPromise;});
 handle('export',async kind=>{const report=kind==='ledger'?ledgerResult:{version:app.getVersion(),accounts:store.settings.accounts.map(a=>({provider:a.provider,status:store.cache[a.id]?.status||'unavailable',source:store.cache[a.id]?.source,observedAt:store.cache[a.id]?.observedAt,error:store.cache[a.id]?.error}))};if(!report)throw Error('Scan history first');const r=await dialog.showSaveDialog(settingsWindow,{defaultPath:`Pulse-${kind}.json`,filters:[{name:'JSON',extensions:['json']}]});if(!r.canceled){fs.writeFileSync(r.filePath,JSON.stringify(report,null,2));return true;}return false;});
 handle('command',action=>{if(action==='settings')showSettings();else if(action==='close')settingsWindow?.close();else if(action==='minimize')settingsWindow?.minimize();else if(action==='maximize'){if(settingsWindow?.isMaximized())settingsWindow.unmaximize();else settingsWindow?.maximize();}else if(action==='menu')menu().popup({window:panel});else if(action==='quit'){app.isQuitting=true;app.quit();}});
 handle('openExternal',url=>{if(typeof url!=='string'||!externalURLs.has(url))throw Error('External URL is not allowed');return shell.openExternal(url).then(()=>true);});
 handle('update',async action=>{if(testMode)return publishUpdate({status:action==='check'?'not-available':'idle',version:app.getVersion()});if(!updaterReady)return publishUpdate({status:'error',message:'Updates are available in the installed app only'});const{autoUpdater}=require('electron-updater');if(action==='check'){await autoUpdater.checkForUpdates();}else if(action==='download'){await autoUpdater.downloadUpdate();}else if(action==='install'&&updateState.status==='downloaded'){setImmediate(()=>autoUpdater.quitAndInstall(false,true));}return updateState;});
 ipcMain.on('hitAreas',(e,rects)=>{if(e.sender!==panel?.webContents||!Array.isArray(rects))return;areas=rects.slice(0,8).filter(r=>['x','y','width','height'].every(k=>Number.isFinite(r[k])));});
 ipcMain.on('drag',(e,action)=>{if(e.sender!==panel?.webContents)return;if(action==='start'){dragging={cursor:screen.getCursorScreenPoint(),bounds:panel.getBounds()};}else if(action==='end'&&dragging){const mouse=screen.getCursorScreenPoint(),d=screen.getDisplayNearestPoint(mouse),b=d.workArea;store.settings.display=d.id;store.settings.position=mouse.x<b.x+70?'left':mouse.x>b.x+b.width-70?'right':mouse.y<b.y+45?'top':'free';store.settings.freePosition=panel.getPosition().reduce((o,n,i)=>({...o,[i?'y':'x']:n}),{});dragging=null;store.save();place(d);broadcast();}});
}
function watch(){watcher=setInterval(()=>{if(!panel||panel.isDestroyed()||!store.settings.visible)return;const p=screen.getCursorScreenPoint();if(dragging){panel.setPosition(dragging.bounds.x+p.x-dragging.cursor.x,dragging.bounds.y+p.y-dragging.cursor.y);return;}const b=panel.getBounds();const inside=areas.some(r=>p.x>=b.x+r.x&&p.x<=b.x+r.x+r.width&&p.y>=b.y+r.y&&p.y<=b.y+r.y+r.height);panel.setIgnoreMouseEvents(!inside,{forward:true});if(store.settings.followDisplay&&Date.now()-lastAutomatic>500){const d=screen.getDisplayNearestPoint(p);if(d.id!==store.settings.display){store.settings.display=d.id;place(d);store.save();}lastAutomatic=Date.now();}},60);}
if(!app.requestSingleInstanceLock())app.quit();else{app.on('second-instance',showSettings);app.whenReady().then(()=>{store=new Storage(app.getPath('userData'),safeStorage);for(const r of Object.values(store.cache))if(r.status==='live')r.status='stale';setupIPC();makePanel();traySetup();watch();schedule();configureUpdater();if(store.settings.shortcut)try{globalShortcut.register(store.settings.shortcut,()=>updateSettings({visible:!store.settings.visible}));}catch{}screen.on('display-removed',()=>place());screen.on('display-metrics-changed',()=>place());if(!process.argv.includes('--background'))showSettings();if(!testMode)refreshAll();});}
app.whenReady().then(()=>watchFullscreen());
app.on('window-all-closed',()=>{});app.on('before-quit',()=>{app.isQuitting=true;fullscreenHelper?.kill();clearInterval(watcher);clearInterval(refreshTimer);globalShortcut.unregisterAll();});
