import React,{useState,useEffect,useRef} from 'react';
import{createRoot}from'react-dom/client';
import{Search,SlidersHorizontal,ChartNoAxesColumn,PanelLeft,Plus,RefreshCw,ChevronRight,Download,Activity,Info,Pin,Trash2,Minus,Square,X,ExternalLink,Github,ShieldCheck}from'lucide-react';
import type{State,Account,Reading,UsageWindow,Ledger,Settings,UpdateState}from'./types';
import'./style.css';
import{dockPath}from'./geometry';
const api=window.pulse;
const isPanel=new URLSearchParams(location.search).get('view')==='panel';
const L=(s:State,en:string,zh:string)=>s.settings.language==='zh'?zh:en;
function Icon({name,className=''}:{name:string;className?:string}){return <img className={`mark ${className}`} src={`./marks/${name}.svg`} alt=""/>;}
function primary(a:Account,r?:Reading){return r?.windows.find(w=>w.id===a.pin)||r?.windows.reduce<UsageWindow|undefined>((best,w)=>!best||w.exhausted||w.used>best.used?w:best,undefined);}
function tint(w?:UsageWindow,warning=75,custom?:string){return w?.exhausted?'#b92530':custom||(!w?'#515151':w.used>=warning?'#ff514c':w.used>=50?'#ffb340':'#00d991');}
function resetLabel(value:string|null,s:State){if(!value)return L(s,'Reset time unavailable','未提供重置时间');const delta=Date.parse(value)-Date.now();if(delta<=0)return L(s,'Awaiting reset','等待刷新重置');const minutes=Math.ceil(delta/60000),h=Math.floor(minutes/60),m=minutes%60;return L(s,`Resets in ${h?`${h}h `:''}${m}m`,`${h?`${h} 小时 `:''}${m} 分钟后重置`);}
function statusText(r:Reading|undefined,s:State){return r?.status==='live'?L(s,'Connected','已连接'):r?.status==='stale'?L(s,'Showing last reading','显示上次读数'):L(s,'Not connected','未连接');}
function message(r:Reading|undefined,s:State){if(!r?.error)return r?.status==='stale'?L(s,'Waiting for the next refresh.','等待下次刷新。'):L(s,'Open Settings to connect this account.','打开设置以连接此账号。');const map:Record<string,string>={'Sign in or configure a credential in Settings':'请先登录对应客户端，或在设置中配置凭据','Login expired or credential rejected':'登录已过期或凭据被拒绝，请重新登录','Rate limited. Please retry later':'请求过于频繁，请稍后重试','Network request failed. Check your connection or system proxy':'网络请求失败，请检查网络或系统代理','No readable quota reported':'服务未返回可读取的额度','Service rejected the request':'服务拒绝了请求，请检查套餐和凭据'};return s.settings.language==='zh'?map[r.error]||r.error:r.error;}
function Ring({a,r,s,icon}:{a:Account;r?:Reading;s:State;icon:string}){const w=primary(a,r),value=w?(s.settings.remaining?100-w.used:w.used):null;const color=tint(w,s.settings.warning,a.color);const circumference=2*Math.PI*16;const second=s.settings.secondRing?r?.windows.find(x=>x.id!==w?.id):null;return <div className={`ring ${s.refreshing.includes(a.id)?'fetching':''}`}>
 <svg viewBox="6 6 36 36" aria-hidden="true"><circle cx="24" cy="24" r="16" fill="none" stroke="#252525" strokeWidth="4"/>{w&&<circle cx="24" cy="24" r="16" fill="none" stroke={color} strokeWidth="4" strokeLinecap="round" strokeDasharray={`${(w.exhausted?100:value!)*circumference/100} ${circumference}`} transform="rotate(-90 24 24)"/>}{second&&<circle cx="24" cy="24" r="11.5" fill="none" stroke={tint(second,s.settings.warning)} strokeWidth="2" strokeDasharray={`${second.used*2*Math.PI*11.5/100} 73`} transform="rotate(-90 24 24)"/>}{s.settings.clock&&w?.seconds&&w.resetsAt&&<circle cx="24" cy="24" r="22" fill="none" stroke="#fff7" strokeWidth="1" strokeDasharray={`${Math.min(1,Math.max(0,1-(Date.parse(w.resetsAt)-Date.now())/(w.seconds*1000)))*138} 138`} transform="rotate(-90 24 24)"/>}</svg>
 <Icon name={icon} className={second?'second':''}/>{s.refreshing.includes(a.id)&&<span className="refresh-dot"/>}</div>;}
function Panel({s}:{s:State}){const accounts=s.settings.accounts.filter(a=>a.enabled);const[hover,setHover]=useState<string|null>(null),[expanded,setExpanded]=useState(false),[pointer,setPointer]=useState(100);const rail=useRef<HTMLDivElement>(null),card=useRef<HTMLDivElement>(null),timer=useRef<ReturnType<typeof setTimeout>>(undefined);const drag=useRef({x:0,y:0,moved:false});const k={small:.85,standard:1,large:1.2}[s.settings.size],top=s.settings.position==='top',left=s.settings.position==='left';const collapsed=s.settings.collapse&&s.settings.position!=='free'&&!expanded;const account=accounts.find(a=>a.id===hover),reading=account?s.readings[account.id]:undefined;
 const enter=()=>{clearTimeout(timer.current);setExpanded(true);};const leave=()=>{clearTimeout(timer.current);timer.current=setTimeout(()=>{setHover(null);setExpanded(false);},550);};
 useEffect(()=>{const update=()=>{if(rail.current){const el=rail.current;el.style.clipPath=!collapsed&&s.settings.position!=='free'?dockPath(el.offsetWidth,el.offsetHeight,top,left,k):'';}const rects=[rail.current,card.current].filter(Boolean).map(el=>{const r=el!.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height};});api?.hitAreas(rects);};update();const tick=setInterval(update,100);return()=>clearInterval(tick);},[collapsed,hover,s.settings]);
 useEffect(()=>{const up=()=>{api?.drag('end');};window.addEventListener('pointerup',up);return()=>{window.removeEventListener('pointerup',up);clearTimeout(timer.current);};},[]);
 const select=(a:Account,e:React.MouseEvent)=>{enter();setHover(a.id);const r=e.currentTarget.getBoundingClientRect();setPointer(top?r.x+r.width/2:r.y+r.height/2);};
 const cardTop=top?82*k:Math.max(8,Math.min(window.innerHeight-(card.current?.offsetHeight||260)-8,pointer-100*k));
 return <div className={`panel ${top?'top':left?'left':'right'} ${s.settings.glass?'glass':''}`} style={{'--scale':k,'--spacing':`${{tight:16,standard:30,loose:40}[s.settings.spacing]}px`} as React.CSSProperties} onContextMenu={e=>{e.preventDefault();api?.command('menu');}}>
  <div ref={rail} className={`rail ${collapsed?'collapsed':''} ${s.settings.position==='free'?'floating':'docked'}`} onMouseEnter={enter} onMouseLeave={leave} onPointerDown={e=>{if(e.button!==0)return;drag.current={x:e.clientX,y:e.clientY,moved:false};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(e.buttons!==1)return;if(!drag.current.moved&&Math.hypot(e.clientX-drag.current.x,e.clientY-drag.current.y)>5){drag.current.moved=true;setHover(null);api?.drag('start');}}} onPointerUp={e=>{if(e.button===0)api?.drag('end');}}>
  <div className="rail-content">{accounts.map(a=><div key={a.id} className={`slot ${a.id===hover?'hovered':''}`} onMouseEnter={e=>select(a,e)} onDoubleClick={()=>api?.command('settings')}>
   <Ring a={a} r={s.readings[a.id]} s={s} icon={s.catalog.find(p=>p.id===a.provider)!.icon}/>{s.settings.percentages&&<span className="percentage">{(()=>{const w=primary(a,s.readings[a.id]);return w?`${Math.round(s.settings.remaining?100-w.used:w.used)}%`:'—';})()}</span>}
  </div>)}</div></div>
  {account&&!collapsed&&<div ref={card} className="usage-card" onMouseEnter={enter} onMouseLeave={leave} style={{top:cardTop,...(top?{left:Math.max(8,Math.min(window.innerWidth-270*k,pointer-125*k))}:{})}}>
   <span className="card-pointer" style={top?{left:Math.max(25,Math.min(220,pointer-(card.current?.offsetLeft||0))/k)}:{top:Math.max(28,Math.min((card.current?.offsetHeight||260)/k-28,(pointer-cardTop)/k))}}/>
   <h3><Icon name={s.catalog.find(p=>p.id===account.provider)!.icon}/>{account.label} <button title={L(s,'Refresh','刷新')} onClick={()=>api?.refresh(account.id)}><RefreshCw size={12} className={s.refreshing.includes(account.id)?'spin':''}/></button></h3>
   {reading?.windows.map(w=><div className="quota" key={w.id}><div className="quota-label">{w.label}</div><div className="progress"><i style={{width:`${w.used}%`,background:tint(w,s.settings.warning,account.color)}}/></div><div className="quota-bottom"><b>{Math.round(s.settings.remaining?100-w.used:w.used)}% {L(s,s.settings.remaining?'Left':'Used',s.settings.remaining?'剩余':'已用')}</b><span>{resetLabel(w.resetsAt,s)}</span></div></div>)}
   {reading?.balance&&<div className="balance">{reading.balance}</div>}
   {(!reading||reading.status!=='live')&&<div className="card-status">{reading?.status==='stale'&&<b>{L(s,'Last reading · ','上次读数 · ')}</b>}{message(reading,s)}</div>}
   <button className="card-link" onClick={()=>api?.command('settings')}>{L(s,'Account settings','账号设置')}<ChevronRight size={12}/></button>
  </div>}
 </div>;}
function Toggle({checked,onChange,label}:{checked:boolean;onChange:()=>void;label:string}){return <button role="switch" aria-checked={checked} aria-label={label} className={`toggle ${checked?'on':''}`} onClick={onChange}><i/></button>;}
function Segments({value,options,onChange}:{value:string|number;options:[string|number,string][];onChange:(v:any)=>void}){return <div className="segments">{options.map(([v,title])=><button key={v} className={v===value?'selected':''} onClick={()=>onChange(v)}>{title}</button>)}</div>;}
function Row({title,description,children}:{title:string;description?:string;children:React.ReactNode}){return <div className="setting-row"><div><div className="row-title">{title}</div>{description&&<div className="row-description">{description}</div>}</div><div className="row-control">{children}</div></div>;}
function General({s,change,run}:{s:State;change:(p:Partial<Settings>)=>void;run:(p:Promise<unknown>)=>void}){const t=(en:string,zh:string)=>L(s,en,zh);const toggle=(key:keyof Settings,title:string,description:string)=><Row title={title} description={description}><Toggle label={title} checked={!!s.settings[key]} onChange={()=>change({[key]:!s.settings[key]})}/></Row>;
 return <><h1>{t('General','通用')}</h1><h2>{t('Floating panel','悬浮面板')}</h2><div className="group">
 {toggle('visible',t('Show floating panel','显示悬浮面板'),t('The usage rail at the edge of your screen.','在屏幕边缘显示额度悬浮条。'))}
 {toggle('hideFullscreen',t('Hide in full screen','全屏时隐藏'),t('Keep the floating panel out of full-screen apps.','使用全屏应用时隐藏悬浮面板。'))}
 <Row title={t('Size','大小')} description={t('Size of the rail on screen.','调整悬浮条在屏幕上的大小。')}><Segments value={s.settings.size} options={[["small",t('Small','小')],["standard",t('Standard','标准')],["large",t('Large','大')]]} onChange={size=>change({size})}/></Row>
 <Row title={t('Spacing','间距')} description={t('How much air there is between the rings.','调整各个额度圆环之间的距离。')}><Segments value={s.settings.spacing} options={[["tight",t('Tight','紧凑')],["standard",t('Standard','标准')],["loose",t('Loose','宽松')]]} onChange={spacing=>change({spacing})}/></Row>
 {toggle('glass',t('Glass appearance','玻璃外观'),t('A translucent surface. Windows approximation of Liquid Glass.','半透明材质，模拟原版 Liquid Glass 的外观。'))}
 {toggle('collapse',t('Hide until pointed at','悬停时展开'),t('Against a screen edge, the rail shrinks to a sliver until you point at it.','贴边时收起为细条，鼠标移入后展开。'))}
 <Row title={t('Position','位置')} description={t('Drag it anywhere; near an edge it snaps on.','拖动悬浮条改变位置，靠近边缘后自动吸附。')}><Segments value={s.settings.position} options={[["left",t('Left','左侧')],["top",t('Top','顶部')],["free",t('Free','自由')],["right",t('Right','右侧')]]} onChange={position=>change({position})}/></Row>
 {toggle('followDisplay',t('Follow the active display','跟随活动显示器'),t('Move the single rail to the display your pointer is on.','将悬浮条移动到鼠标所在的显示器。'))}
 {toggle('percentages',t('Percentages at the side','显示百分比'),t('The figure beneath each ring.','在额度圆环下方显示百分比。'))}
 </div><h2>{t('Readings & appearance','额度与外观')}</h2><div className="group">
 {toggle('remaining',t('Show remaining allowance','显示剩余额度'),t('Show what is left instead of what has been used.','切换显示已用额度或剩余额度。'))}
 {toggle('secondRing',t('Second limit ring','第二额度圆环'),t('An inner ring for another reported limit.','用内环显示服务返回的第二个额度窗口。'))}
 {toggle('clock',t('Window elapsed arc','时间进度弧'),t('Show elapsed time when the provider reports a window length.','服务提供周期长度时，在外侧显示时间进度。'))}
 <Row title={t('Warning threshold','警告阈值')} description={t('The usage level at which the ring becomes red.','额度达到该比例时，圆环变为红色。')}><select value={s.settings.warning} onChange={e=>change({warning:Number(e.target.value)})}>{[60,70,75,80,90].map(v=><option key={v} value={v}>{v}%</option>)}</select></Row>
 <Row title={t('Refresh interval','刷新间隔')} description={t('Only enabled accounts refresh in the background.','仅在后台刷新已启用的账号。')}><select value={s.settings.refreshSeconds} onChange={e=>change({refreshSeconds:Number(e.target.value)})}>{[60,120,300,600].map(v=><option key={v} value={v}>{v/60} {t('minutes','分钟')}</option>)}</select></Row>
 </div><h2>{t('System','系统')}</h2><div className="group">{toggle('launchAtLogin',t('Launch at login','开机启动'),t('Start Pulse when you sign in to Windows.','登录 Windows 后自动启动 Pulse。'))}{toggle('notifications',t('Quota notifications','额度通知'),t('Notify at 75%, 80%, 90%, 95% and 100% used.','额度达到 75%、80%、90%、95%、100% 时通知。'))}
 <Row title={t('Language','语言')}><Segments value={s.settings.language} options={[["en","English"],["zh","简体中文"]]} onChange={language=>change({language})}/></Row>
 <Row title={t('Panel shortcut','悬浮窗快捷键')} description={t('Show or hide the floating panel.','显示或隐藏悬浮面板。')}><select value={s.settings.shortcut} onChange={e=>change({shortcut:e.target.value})}><option value="">{t('None','无')}</option><option value="CommandOrControl+Shift+P">Ctrl + Shift + P</option><option value="CommandOrControl+Alt+P">Ctrl + Alt + P</option></select></Row>
 </div><div className="footer-note">Pulse {s.version} · Windows<br/>{t('Independent Windows port of qunqin24/Pulse. Local-first, no Pulse account.','基于 qunqin24/Pulse 的独立 Windows 移植版。数据保存在本机，无需 Pulse 账号。')}</div><button className="text-button" onClick={()=>run(api!.export('diagnostics'))}><Download size={14}/>{t('Export diagnostics','导出诊断报告')}</button></>;}
function AccountPage({s,a,run}:{s:State;a:Account;run:(p:Promise<unknown>)=>void}){const p=s.catalog.find(p=>p.id===a.provider)!;const r=s.readings[a.id];const t=(en:string,zh:string)=>L(s,en,zh);const[key,setKey]=useState(''),[label,setLabel]=useState(a.label),[confirm,setConfirm]=useState(false);const change=(patch:Partial<Account>)=>run(api!.account({...a,...patch}));return <>
 <div className="page-heading"><h1><Icon name={p.icon}/>{a.label}</h1><button className="button" disabled={s.refreshing.includes(a.id)||!p.available} onClick={()=>run(api!.refresh(a.id))}><RefreshCw size={14} className={s.refreshing.includes(a.id)?'spin':''}/>{t('Refresh','刷新')}</button></div>
 <div className="connection"><span className={`status-dot ${r?.status||''}`}/>{!p.available?t('Windows connector not yet available','Windows 接入尚未适配'):statusText(r,s)}{r?.observedAt&&<span className="last-check">{new Date(r.observedAt).toLocaleString(s.settings.language==='zh'?'zh-CN':'en-US')}</span>}</div>
 {!p.available&&<div className="notice">{t('This provider is listed to preserve the original account catalog. This release does not read its Windows quota yet.','保留原版服务目录；当前版本尚不能读取此服务在 Windows 上的额度。')}</div>}
 {p.available&&r?.error&&<div className="notice">{message(r,s)}</div>}
 <h2>{t('Account','账号')}</h2><div className="group"><Row title={t('Show in floating panel','在悬浮条中显示')}><Toggle label="Show account" checked={a.enabled} onChange={()=>change({enabled:!a.enabled})}/></Row>
 <Row title={t('Label','名称')}><input className="input" value={label} onChange={e=>setLabel(e.target.value)} onBlur={()=>{if(label.trim()&&label!==a.label)change({label:label.trim()});}} maxLength={60}/></Row>
 <Row title={t('Ring color','圆环颜色')} description={t('Automatic colors reflect usage.','默认颜色随额度使用情况变化。')}><input type="color" aria-label="Ring color" value={a.color||'#00d991'} onChange={e=>change({color:e.target.value})}/><button className="text-button" onClick={()=>change({color:''})}>{t('Automatic','自动')}</button></Row>
 {r?.plan&&<Row title={t('Plan','套餐')}><span>{r.plan}</span></Row>}{r?.balance&&<Row title={t('Credit balance','账户余额')}><strong>{r.balance}</strong></Row>}
 </div><h2>{t('Connection','连接')}</h2><div className="group">
 <Row title={t('Reading source','读取来源')} description={p.auth==='oauth'?t('Uses the existing local CLI login. Custom directories also support WSL.','读取本地 CLI 登录状态；可选择自定义目录以支持 WSL。'):t('Queries this provider directly with your saved credential.','使用保存在本机的凭据直接查询该服务。')}><span className="tag">{r?.source||t('Automatic','自动')}</span></Row>
 {['codex','claude'].includes(a.provider)&&<Row title={t('Client data directory','客户端数据目录')} description={a.dataPath||t('Default user directory','默认用户目录')}><button className="button" onClick={()=>run(api!.choosePath(a.id))}>{t('Choose…','选择…')}</button></Row>}
 {p.available&&p.auth!=='local'&&<Row title={a.provider==='devin'?t('Token + organization (JSON)','令牌与组织（JSON）'):p.auth==='cookie'?t('Session token','会话令牌'):p.auth==='key'?'API Key':t('Access token (optional)','访问令牌（可选）')} description={s.configured.includes(a.id)?t('Saved with Windows encryption. Never displayed.','已使用 Windows 加密保存，不回显凭据。'):a.provider==='devin'?t('Format: {"token":"…","org":"…"}','格式：{"token":"…","org":"…"}'):p.auth==='local'?t('Keep the local client running and signed in.','请保持本地客户端运行且已登录。'):t('Leave empty to use the local login when supported.','支持本地登录时可留空。')}><div className="credential"><input type="password" className="input" autoComplete="off" value={key} placeholder={s.configured.includes(a.id)?'••••••••':t('Paste credential','粘贴凭据')} onChange={e=>setKey(e.target.value)}/><button className="button" disabled={!key.trim()} onClick={()=>{run(api!.credential(a.id,key));setKey('');}}>{t('Save','保存')}</button>{s.configured.includes(a.id)&&<button className="icon-button" title={t('Remove saved credential','清除已存凭据')} onClick={()=>run(api!.credential(a.id,''))}><Trash2 size={14}/></button>}</div></Row>}
 </div>
 <h2>{t('Reported limits','服务返回的额度')}</h2>{r?.windows.length?<div className="group limit-group">{r.windows.map(w=><div className="limit-row" key={w.id}><div className="limit-heading"><b>{w.label}</b><button className={`icon-button ${a.pin===w.id?'pinned':''}`} title={t('Pin this limit to the ring','在圆环上固定显示该额度')} onClick={()=>change({pin:a.pin===w.id?'':w.id})}><Pin size={14}/></button></div><div className="progress"><i style={{width:`${w.used}%`,background:tint(w,s.settings.warning,a.color)}}/></div><div className="limit-bottom"><b>{Math.round(w.used)}% {t('used','已用')}</b><span>{resetLabel(w.resetsAt,s)}</span></div></div>)}</div>:<div className="empty-state"><Activity size={28}/><b>{t('No quota reading yet','暂无额度读数')}</b><span>{p.available?t('Connect your account, then refresh. Missing data is never shown as zero.','连接账号后点击刷新。缺失数据不会显示为零。'):t('This connector needs a Windows adapter.','此服务仍需适配 Windows 读取方式。')}</span></div>}
 <div className="account-bottom">{confirm?<><span>{t('Remove this account?','移除此账号？')}</span><button className="button danger" onClick={()=>run(api!.remove(a.id))}>{t('Remove','移除')}</button><button className="button" onClick={()=>setConfirm(false)}>{t('Cancel','取消')}</button></>:<button className="text-button danger" onClick={()=>setConfirm(true)}><Trash2 size={14}/>{t('Remove account','移除账号')}</button>}</div>
 </>;}
const compact=(n:number)=>Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(n);
function Spend({s,run}:{s:State;run:(p:Promise<unknown>)=>void}){const[days,setDays]=useState(7),[data,setData]=useState<Ledger>(),[busy,setBusy]=useState(false),[agent,setAgent]=useState('all');const t=(en:string,zh:string)=>L(s,en,zh);const scan=()=>{setBusy(true);api!.ledger(days).then(setData).finally(()=>setBusy(false));};useEffect(scan,[days]);const rows=data?.rows.filter(r=>agent==='all'||r.agent===agent)||[];const input=rows.reduce((n,r)=>n+r.input,0),output=rows.reduce((n,r)=>n+r.output,0),cached=rows.reduce((n,r)=>n+r.cached,0);const modelMap=new Map<string,{input:number;output:number;cached:number}>();const dayMap=new Map<string,number>();for(const r of rows){const v=modelMap.get(r.model)||{input:0,output:0,cached:0};v.input+=r.input;v.output+=r.output;v.cached+=r.cached;modelMap.set(r.model,v);dayMap.set(r.day,(dayMap.get(r.day)||0)+r.input+r.output);}const series=[...dayMap.entries()].sort((a,b)=>a[0].localeCompare(b[0]));const max=Math.max(1,...series.map(x=>x[1]));return <>
 <div className="page-heading"><h1>{t('Token spend','Token 用量')}</h1><button className="button" onClick={scan} disabled={busy}><RefreshCw size={14} className={busy?'spin':''}/>{t('Refresh','刷新')}</button></div>
 <div className="spend-toolbar"><Segments value={days} options={[[7,t('7 days','7 天')],[30,t('30 days','30 天')],[90,t('90 days','90 天')]]} onChange={setDays}/><select value={agent} onChange={e=>setAgent(e.target.value)}><option value="all">{t('All agents','所有工具')}</option><option>Codex</option><option>Claude Code</option></select></div>
 <div className="spend-summary"><span>{t('Total tokens','总 Token 数')}</span><strong>{compact(input+output)}</strong><p>{t('Local usage records · Codex & Claude Code','本地使用记录 · Codex 与 Claude Code')}</p></div>
 <div className="token-stats">{[[t('Input','输入'),input],[t('Output','输出'),output],[t('Cached input','缓存输入'),cached]].map(([name,value])=><div key={name}><span>{name}</span><b>{compact(Number(value))}</b></div>)}</div>
 <h2>{t('Daily activity','每日使用量')}</h2><div className="chart group">{series.length?<div className="bars">{series.map(([day,n])=><div className="bar-column" key={day} title={`${day}: ${n.toLocaleString()} tokens`}><i style={{height:`${Math.max(2,n/max*145)}px`}}/><span>{day.slice(5)}</span></div>)}</div>:<div className="empty-state"><ChartNoAxesColumn size={30}/><b>{busy?t('Reading local usage…','正在读取本地记录…'):t('No records in this period','该时段暂无使用记录')}</b><span>{t('Use Codex or Claude Code, then refresh.','使用 Codex 或 Claude Code 后，再刷新查看。')}</span></div>}</div>
 <h2>{t('Models','模型')}</h2><div className="group table-wrap"><table><thead><tr><th>{t('Model','模型')}</th><th>{t('Input','输入')}</th><th>{t('Output','输出')}</th><th>{t('Cached','缓存')}</th></tr></thead><tbody>{[...modelMap].sort((a,b)=>b[1].input+b[1].output-a[1].input-a[1].output).map(([name,v])=><tr key={name}><td>{name}</td><td>{compact(v.input)}</td><td>{compact(v.output)}</td><td>{compact(v.cached)}</td></tr>)}{!modelMap.size&&<tr><td colSpan={4} className="muted">{t('No model usage available','暂无模型使用数据')}</td></tr>}</tbody></table></div>
 <p className="footnote">{t('Reads token counters only; conversations are not stored. Costs are not estimated without verified prices. Cached input is included in input, not added again.','仅提取 Token 计数，不保存对话内容。未获取可靠价格时不估算费用；缓存输入已计入输入，不重复相加。')}<br/>{data&&`${t('Files read','已读取文件')} ${data.filesRead} · ${t('Skipped or limited','跳过或受限')} ${data.skipped}`}{data?.error&&t(' · Scan failed or timed out',' · 扫描失败或超时')}</p><button className="text-button" disabled={!data} onClick={()=>run(api!.export('ledger'))}><Download size={14}/>{t('Export usage data','导出使用数据')}</button>
 </>;}
function About({s,run}:{s:State;run:(p:Promise<unknown>)=>void}){const t=(en:string,zh:string)=>L(s,en,zh);const[update,setUpdate]=useState<UpdateState>({status:'idle'});useEffect(()=>api?.onUpdate(setUpdate),[]);const open=(url:string)=>run(api!.openExternal(url));const action=(name:'check'|'download'|'install')=>run(api!.update(name).then(value=>{setUpdate(value);return value;}));const status=update.status==='checking'?t('Checking for updates…','正在检查更新…'):update.status==='available'?t(`Pulse ${update.version||''} is available.`,`发现新版本 Pulse ${update.version||''}。`):update.status==='downloading'?t(`Downloading ${Math.round(update.percent||0)}%…`,`正在下载 ${Math.round(update.percent||0)}%…`):update.status==='downloaded'?t(`Pulse ${update.version||''} is ready to install.`,`Pulse ${update.version||''} 已可安装。`):update.status==='not-available'?t('You are using the latest version.','当前已是最新版本。'):update.status==='error'?t('Update check failed. Open Releases to download manually.','更新检查失败，可打开 Releases 手动下载。'):t('Updates are delivered from the Windows repository Releases.','更新由 Windows 版仓库的 Releases 提供。');return <>
 <div className="about-hero"><img src="./icon.png" alt="Pulse"/><div><h1>Pulse for Windows</h1><p>{t('Version','版本')} {s.version}</p></div></div>
 <p className="about-copy">{t('A Windows port of Pulse for monitoring AI coding usage and limits.','Pulse 的 Windows 移植版，用于查看 AI 编程工具的用量与额度。')}</p>
 <h2>{t('Source & license','源代码与许可')}</h2><div className="group about-links">
  <button onClick={()=>open('https://github.com/qunqin24/Pulse')}><Github size={21}/><span><b>{t('Original Pulse repository','Pulse 来源仓库')}</b><small>github.com/qunqin24/Pulse</small></span><ExternalLink size={15}/></button>
  <button onClick={()=>open('https://github.com/qunqin24/Pulse/blob/main/LICENSE')}><ShieldCheck size={21}/><span><b>Apache License 2.0</b><small>{t('This Windows port follows the original project license.','本 Windows 移植版依据原项目许可发布。')}</small></span><ExternalLink size={15}/></button>
  <button onClick={()=>open('https://github.com/dcxa521gi/Pulse-Win')}><Github size={21}/><span><b>{t('Windows repository','Windows 版项目仓库')}</b><small>github.com/dcxa521gi/Pulse-Win</small></span><ExternalLink size={15}/></button>
 </div>
 <h2>{t('Software update','软件更新')}</h2><div className="group update-box"><div><b>{status}</b>{update.message&&<small>{update.message}</small>}</div><div className="update-actions">{update.status==='available'&&<button className="button primary" onClick={()=>action('download')}><Download size={14}/>{t('Download update','下载更新')}</button>}{update.status==='downloaded'&&<button className="button primary" onClick={()=>action('install')}>{t('Restart and install','重启安装')}</button>}<button className="button" disabled={update.status==='checking'||update.status==='downloading'} onClick={()=>action('check')}><RefreshCw size={14} className={update.status==='checking'?'spin':''}/>{t('Check for updates','检查更新')}</button><button className="text-button" onClick={()=>open('https://github.com/dcxa521gi/Pulse-Win/releases')}>Releases <ExternalLink size={13}/></button></div></div>
 <p className="footnote">{t('Pulse checks for a newer release shortly after startup. Downloads start only after you confirm.','Pulse 会在启动后检查新版本，确认后才会下载更新。')}</p>
 </>;}
function App({s,setState}:{s:State;setState:(s:State)=>void}){const[page,setPage]=useState('general'),[query,setQuery]=useState(''),[adding,setAdding]=useState(false),[error,setError]=useState('');const t=(en:string,zh:string)=>L(s,en,zh);const run=(promise:Promise<unknown>)=>{promise.then(r=>{if(r&&typeof r==='object'&&'settings'in r)setState(r as State);setError('');}).catch(()=>setError(t('Could not complete this action. Check the account, shortcut, network, or update source.','操作未完成。请检查账号、快捷键、网络或更新来源。')));};const current=s.settings.accounts.find(a=>a.id===page);useEffect(()=>{if(page!=='general'&&page!=='spend'&&page!=='about'&&!current)setPage('general');},[s.settings.accounts]);return <div className="settings-app">
 <aside className="sidebar"><div className="sidebar-header"><div className="traffic"><button className="red" title="Close" onClick={()=>api?.command('close')}/><button className="yellow" title="Minimize" onClick={()=>api?.command('minimize')}/><button className="green" title="Maximize" onClick={()=>api?.command('maximize')}/></div><PanelLeft size={20}/></div>
 <div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('Search','搜索')}/>{query&&<button onClick={()=>setQuery('')}><X size={12}/></button>}</div><nav><div className="nav-label">{t('Panel','面板')}</div>{[['general',t('General','通用'),SlidersHorizontal],['spend',t('Token spend','Token 用量'),ChartNoAxesColumn],['about',t('About','关于'),Info]].map(([id,title,Mark])=>{const M=Mark as typeof Info;return <button className={`nav-item ${page===id?'active':''}`} key={id as string} onClick={()=>setPage(id as string)}><M size={20}/><span>{title as string}</span></button>;})}<div className="nav-label accounts-label">{t('Accounts','账号')}<button className="icon-button" title={t('Add account','添加账号')} onClick={()=>setAdding(true)}><Plus size={15}/></button></div>
 {s.settings.accounts.filter(a=>a.label.toLowerCase().includes(query.toLowerCase())).map(a=><button className={`nav-item ${page===a.id?'active':''} ${!a.enabled?'disabled-account':''}`} key={a.id} onClick={()=>setPage(a.id)}><Icon name={s.catalog.find(p=>p.id===a.provider)!.icon}/><span>{a.label}</span>{s.readings[a.id]?.status==='live'&&<i className="nav-status"/>}</button>)}<button className="nav-item add-account" onClick={()=>setAdding(true)}><Plus size={19}/>{t('Add account','添加账号')}</button></nav><div className="sidebar-footer"><span className="pulse-dot"/>Pulse <span>Windows · {s.version}</span></div></aside>
 <main className="main"><header className="titlebar"><b>{t('Pulse Settings','Pulse 设置')}</b><div className="window-controls"><button title="Minimize" onClick={()=>api?.command('minimize')}><Minus size={14}/></button><button title="Maximize" onClick={()=>api?.command('maximize')}><Square size={11}/></button><button title="Close" onClick={()=>api?.command('close')}><X size={15}/></button></div></header><div className="content" key={page}>{error&&<div role="alert" className="notice">{error}<button onClick={()=>setError('')}><X size={13}/></button></div>}{page==='general'?<General s={s} change={p=>run(api!.settings(p))} run={run}/>:page==='spend'?<Spend s={s} run={run}/>:page==='about'?<About s={s} run={run}/>:current?<AccountPage key={current.id} s={s} a={current} run={run}/>:null}</div></main>
 {adding&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setAdding(false);}}><div className="modal" role="dialog" aria-modal="true" aria-label={t('Add account','添加账号')}><div className="page-heading"><h2>{t('Add account','添加账号')}</h2><button className="icon-button" onClick={()=>setAdding(false)}><X size={18}/></button></div><p>{t('Choose a service to monitor.','选择要监控的服务。')}</p><div className="provider-list">{s.catalog.map(p=><button key={p.id} onClick={()=>{run(api!.account({id:'',provider:p.id,label:p.name,enabled:true}));setAdding(false);}}><Icon name={p.icon}/><span>{p.name}</span>{!p.available?<small>{t('Not yet adapted','待适配')}</small>:<ChevronRight size={15}/>}</button>)}</div></div></div>}
 </div>;}
function Root(){const[s,setState]=useState<State>(),[failed,setFailed]=useState(false);useEffect(()=>{if(!api){setFailed(true);return;}api.state().then(setState).catch(()=>setFailed(true));return api.onState(setState);},[]);return s?isPanel?<Panel s={s}/>:<App s={s} setState={setState}/>:<div className="boot">{failed?'Please launch Pulse from the installed Windows app.':'Pulse'}</div>;}
document.body.className=isPanel?'panel-body':'settings-body';createRoot(document.getElementById('root')!).render(<Root/>);
